name: "Test"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v7
      - uses: cachix/install-nix-action@v31
      - uses: cachix/cachix-action@v17
        with:
          name: meenzen
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
          extraPullNames: devenv

      - name: Install tools
        run: nix profile install nixpkgs#devenv

      - name: Set up devenv
        run: devenv allow

      - name: Install dependencies
        run: devenv shell bun install

      - name: Run devenv tests
        run: devenv test

      - name: Build project
        run: devenv shell bun run build
